context:
  version: "2.1.0"

package:
  name: ultralytics-thop
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/u/ultralytics-thop/ultralytics_thop-${{ version }}.tar.gz
    sha256: 3819e5ad242d0e2d14768fbfd8ed214c9f3531100c0fc81e8f58176faf1c1d28

build:
  number: 0
  script: ${{ PYTHON }} -m pip install .
  noarch: python

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools >=70.0.0
    - pip
  run:
    - python >=${{ python_min }}
    - numpy
    - pytorch

tests:
  - python:
      imports:
        - thop
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: Ultralytics THOP package for fast computation of PyTorch model FLOPs and parameters.
  homepage: https://github.com/ultralytics/thop
  license: AGPL-3.0-only
  license_file: LICENSE
  documentation: https://docs.ultralytics.com

extra:
  recipe-maintainers:
    - carlodri
